// <auto-generated />
namespace MakeIt.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class MakeItDBv3ExceptionDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MakeItDBv3ExceptionDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201911282347465_MakeItDB-v3-ExceptionDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
